config:
  benchmark_suite_path: .
  phase_orders_path: ./sequences.json
  benchmark_timeout_in_s: 300
metadata:
  benchmark_suite_name: PolyBench 4.2.1
  toolchain: LLVM 12.0.1
  dataset_size: mini
  target: AArch64
